#cloud-config
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOtT0RNvJ/pzz/RGSOc5Fo9j7kiAQLijbSVHs/HVJhb4

hostname: kube01

k3os:
  modules:
    - kvm
  server_url: https://kube-master:6443
  k3s_args:
  - server
  - "--disable-agent"
