#cloud-config
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOtT0RNvJ/pzz/RGSOc5Fo9j7kiAQLijbSVHs/HVJhb4

rancher:
  system_docker:
    selinux_enabled: true
  docker:
    selinux_enabled: true
  services:
    rancher-server:
      image: rancher/rancher:stable
      ports:
        - 443:443
        - 80:80
      restart: always
      volumes:
        - /mnt/rancher-server-mysql:/var/lib/mysql

mounts:
  - ["/dev/vdb1", "/mnt", "ext4", ""] 
