#cloud-config
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOtT0RNvJ/pzz/RGSOc5Fo9j7kiAQLijbSVHs/HVJhb4 corey@eos

rancher:
  services:
    rancher-server:
      image: rancher/server:stable
      ports:
        - 8080:8080
        - 443:80
      restart: always
      volumes:
        - /mnt/rancher-server-mysql:/var/lib/mysql

mounts:
 - ["/dev/vdb1", "/mnt", "ext4", ""] 

